/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import entity.Room;
import entity.RoomStatusType;
import entity.RoomType;
import javax.swing.JPanel;
import java.awt.*; 
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author KHANH PC
 */
public class UI_Phong extends javax.swing.JPanel {

    /**
     * Creates new form UI_Phong
     */
//    public UI_Phong() {
////        initComponents();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(61, 139, 233));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 2, true));
        jPanel1.setMinimumSize(new java.awt.Dimension(225, 210));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("101");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Giường đơn");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-checkmark-48.png"))); // NOI18N
        jLabel1.setName(""); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.getAccessibleContext().setAccessibleParent(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        jLabel1.setVisible(!jLabel1.isVisible()); 
 
    }//GEN-LAST:event_formMouseClicked
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    
    Room phong = null; 
    public UI_Phong( Room phong1) {
        phong = phong1; 
        Color colorTrong = new Color(70, 141, 188); 
        Color colorDonDep = new Color(181, 171, 107); 
        Color colorBaoTri = new Color(255, 201, 14); 
        Color colorCoKhach = new Color(255, 40, 0); 
        Color colorDaDat = new Color(181, 230, 29);
        String typeDon = "Giường đơn"; 
        String typeDoi = "Giường đôi"; 
        String typeDoiLon = "Giường đôi lớn"; 
        
        
        initComponents();
        jLabel1.setVisible(false);
        
        
        jLabel4.setText("Giường đơn");
        if(phong.getRoomType().getRoomTypeID().equals("LP002"))
            jLabel4.setText("Giường đôi");
        if(phong.getRoomType().getRoomTypeID().equals("LP003"))
            jLabel4.setText("Giường đôi lớn");
        

        if( phong.getRoomStatusType().getRoomStatusTypeID().equals("LTTP001") ) {
            jPanel1.setBackground(colorTrong);
        }
        if( phong.getRoomStatusType().getRoomStatusTypeID().equals("LTTP002") ) 
            jPanel1.setBackground(colorCoKhach);
        if( phong.getRoomStatusType().getRoomStatusTypeID().equals("LTTP003") ) 
            jPanel1.setBackground(colorDaDat);
        if( phong.getRoomStatusType().getRoomStatusTypeID().equals("LTTP004") ) 
            jPanel1.setBackground(colorBaoTri);
        if( phong.getRoomStatusType().getRoomStatusTypeID().equals("LTTP005") ) 
            jPanel1.setBackground(colorDonDep);

        jLabel3.setText(phong.getRoomID());
    }
    
    public JPanel getBGR() {
        return jPanel1; 
    }
    
    public Room getRoom() {
        return phong; 
    }
    
    public boolean isSelect() {
        return jLabel1.isVisible(); 
    }
}
