/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;


import java.util.ArrayList;
import java.util.List;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ACER
 */
public class GD_QLPhong extends javax.swing.JInternalFrame {
//    private final DefaultTableModel modelNhanVien;
//    private String username;
//    private DAO_NhanVien nvDAO;
//    private DAO_LoaiNhanVien lnvDAO;
//    private DAO_TaiKhoan tkDAO;
    List<RowFilter<DefaultTableModel,Object>> filters = new ArrayList<>();
    private TableRowSorter<DefaultTableModel> tr;

    

    /**
     * Creates new form QuanLyHoaDon
     */
    public GD_QLPhong() {
        this.setRootPaneCheckingEnabled(false);
        javax.swing.plaf.InternalFrameUI ui
                = this.getUI();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) ui).setNorthPane(null);
        initComponents();
        this.setFocusable(true);
//        username=_username;
//        
//        try {
//             ConnectDB.getInstance().connect();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        
//        lnvDAO = new DAO_LoaiNhanVien();
//        nvDAO = new DAO_NhanVien();
//        modelNhanVien=(DefaultTableModel) tblNhanVien.getModel();
//        tkDAO=new DAO_TaiKhoan();
//        docDuLieuLenTable(nvDAO.layTatCaNhanVienDangLamVaoBang(),modelNhanVien);
//        tr=new TableRowSorter<DefaultTableModel>(modelNhanVien);
//        tblNhanVien.setRowSorter(tr);
//        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMain = new javax.swing.JPanel();
        pnlTren = new javax.swing.JPanel();
        pnlThongTin = new javax.swing.JPanel();
        txtTenNhanVien = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbChucVu1 = new javax.swing.JComboBox<>();
        cmbChucVu6 = new javax.swing.JComboBox<>();
        pnlNut = new javax.swing.JPanel();
        btnThemNhanVien = new javax.swing.JButton();
        btnXoaTrang = new javax.swing.JButton();
        btnSuaThongTinNV = new javax.swing.JButton();
        btnXoaNhanVien = new javax.swing.JButton();
        pnlGiua = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtTenNhanVien1 = new javax.swing.JTextField();
        cmbChucVu2 = new javax.swing.JComboBox<>();
        cmbChucVu3 = new javax.swing.JComboBox<>();
        cmbChucVu4 = new javax.swing.JComboBox<>();
        cmbChucVu5 = new javax.swing.JComboBox<>();
        cmbChucVu = new javax.swing.JComboBox<>();
        pnlDuoi = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();

        setBorder(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setFrameIcon(null);
        getContentPane().setLayout(new javax.swing.OverlayLayout(getContentPane()));

        pnlMain.setBackground(new java.awt.Color(252, 210, 165));
        pnlMain.setLayout(new javax.swing.BoxLayout(pnlMain, javax.swing.BoxLayout.Y_AXIS));

        pnlTren.setBackground(new java.awt.Color(252, 210, 165));
        pnlTren.setMaximumSize(new java.awt.Dimension(2147483647, 340));
        pnlTren.setMinimumSize(new java.awt.Dimension(100, 200));
        pnlTren.setPreferredSize(new java.awt.Dimension(1324, 340));
        pnlTren.setLayout(new java.awt.BorderLayout());

        pnlThongTin.setBackground(new java.awt.Color(252, 210, 165));
        pnlThongTin.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 102)), "Thông tin phòng\n", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 14))); // NOI18N
        pnlThongTin.setToolTipText("");
        pnlThongTin.setMaximumSize(new java.awt.Dimension(841, 32767));
        pnlThongTin.setPreferredSize(new java.awt.Dimension(980, 270));

        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTenNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVienActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel4.setText("Mã phòng :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel6.setText("Mô tả : ");

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtCMND.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCMNDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel7.setText("Tên phòng: ");

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtSoDienThoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoDienThoaiActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel8.setText("Loại phòng: ");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel10.setText("Trạng thái: ");

        cmbChucVu1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi nhỏ", "Giường đôi lớn" }));

        cmbChucVu6.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống ", "Đã được thuê", "Đã đặt trước", "Bảo trì", "Dọn dẹp" }));
        cmbChucVu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucVu6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlThongTinLayout = new javax.swing.GroupLayout(pnlThongTin);
        pnlThongTin.setLayout(pnlThongTinLayout);
        pnlThongTinLayout.setHorizontalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(68, 68, 68)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtSoDienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                        .addComponent(txtTenNhanVien)
                        .addGroup(pnlThongTinLayout.createSequentialGroup()
                            .addComponent(cmbChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10)
                            .addGap(52, 52, 52)
                            .addComponent(cmbChucVu6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 742, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        pnlThongTinLayout.setVerticalGroup(
            pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlThongTinLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbChucVu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8))
                    .addGroup(pnlThongTinLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmbChucVu6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlThongTinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtCMND, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        pnlTren.add(pnlThongTin, java.awt.BorderLayout.WEST);

        pnlNut.setBackground(new java.awt.Color(252, 210, 165));
        pnlNut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlNut.setMaximumSize(new java.awt.Dimension(300, 32767));
        pnlNut.setPreferredSize(new java.awt.Dimension(300, 270));

        btnThemNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnThemNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/them.png"))); // NOI18N
        btnThemNhanVien.setText("Thêm phòng");
        btnThemNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnThemNhanVien.setIconTextGap(20);
        btnThemNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemNhanVienActionPerformed(evt);
            }
        });

        btnXoaTrang.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoaTrang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoaTrang.png"))); // NOI18N
        btnXoaTrang.setText("Xóa trắng");
        btnXoaTrang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaTrang.setIconTextGap(20);
        btnXoaTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTrangActionPerformed(evt);
            }
        });

        btnSuaThongTinNV.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSuaThongTinNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/capNhat.png"))); // NOI18N
        btnSuaThongTinNV.setText("Cập nhật thông tin phòng");
        btnSuaThongTinNV.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSuaThongTinNV.setIconTextGap(20);
        btnSuaThongTinNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinNVActionPerformed(evt);
            }
        });

        btnXoaNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnXoaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/xoa.png"))); // NOI18N
        btnXoaNhanVien.setText("Xoá phòng");
        btnXoaNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnXoaNhanVien.setIconTextGap(20);
        btnXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaNhanVienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlNutLayout = new javax.swing.GroupLayout(pnlNut);
        pnlNut.setLayout(pnlNutLayout);
        pnlNutLayout.setHorizontalGroup(
            pnlNutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThemNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSuaThongTinNV, javax.swing.GroupLayout.DEFAULT_SIZE, 2682, Short.MAX_VALUE)
            .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnXoaTrang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlNutLayout.setVerticalGroup(
            pnlNutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlNutLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnThemNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSuaThongTinNV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXoaTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pnlTren.add(pnlNut, java.awt.BorderLayout.CENTER);

        pnlMain.add(pnlTren);

        pnlGiua.setBackground(new java.awt.Color(252, 210, 165));
        pnlGiua.setMaximumSize(new java.awt.Dimension(32767, 50));
        pnlGiua.setPreferredSize(new java.awt.Dimension(3666, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel11.setText("Loại phòng: ");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel13.setText("Tìm kiếm :");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel14.setText("Trạng thái :");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel12.setText("Mã phòng:");

        txtTenNhanVien1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        txtTenNhanVien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenNhanVien1ActionPerformed(evt);
            }
        });

        cmbChucVu2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi nhỏ", "Giường đôi lớn" }));

        cmbChucVu3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi nhỏ", "Giường đôi lớn" }));

        cmbChucVu4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giường đơn", "Giường đôi nhỏ", "Giường đôi lớn" }));

        cmbChucVu5.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống ", "Đã được thuê", "Đã đặt trước", "Bảo trì", "Dọn dẹp" }));
        cmbChucVu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucVu5ActionPerformed(evt);
            }
        });

        cmbChucVu.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        cmbChucVu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trống ", "Đã được thuê", "Đã đặt trước", "Bảo trì", "Dọn dẹp" }));
        cmbChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbChucVuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlGiuaLayout = new javax.swing.GroupLayout(pnlGiua);
        pnlGiua.setLayout(pnlGiuaLayout);
        pnlGiuaLayout.setHorizontalGroup(
            pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiuaLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(44, 44, 44)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChucVu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2724, Short.MAX_VALUE))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(1699, 1699, 1699)
                    .addComponent(cmbChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1699, Short.MAX_VALUE)))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(1699, 1699, 1699)
                    .addComponent(cmbChucVu3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1699, Short.MAX_VALUE)))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(1708, 1708, 1708)
                    .addComponent(cmbChucVu5, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(1709, Short.MAX_VALUE)))
        );
        pnlGiuaLayout.setVerticalGroup(
            pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGiuaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel12)
                    .addComponent(txtTenNhanVien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChucVu4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(cmbChucVu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(cmbChucVu3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
            .addGroup(pnlGiuaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlGiuaLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(cmbChucVu5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        pnlMain.add(pnlGiua);

        pnlDuoi.setBackground(new java.awt.Color(252, 210, 165));
        pnlDuoi.setMaximumSize(new java.awt.Dimension(2147483647, 500));
        pnlDuoi.setPreferredSize(new java.awt.Dimension(1314, 440));
        pnlDuoi.setLayout(new javax.swing.BoxLayout(pnlDuoi, javax.swing.BoxLayout.LINE_AXIS));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(452, 200));

        tblNhanVien.setAutoCreateRowSorter(true);
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã ", "Tên phòng", "Loại phòng", "Trạng thái", "Mô tả"
            }
        ));
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        pnlDuoi.add(jScrollPane1);

        pnlMain.add(pnlDuoi);

        getContentPane().add(pnlMain);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTenNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVienActionPerformed

    private void txtCMNDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCMNDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCMNDActionPerformed

    private void txtSoDienThoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoDienThoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoDienThoaiActionPerformed

    private void btnThemNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemNhanVienActionPerformed
//        if (checkData()){
//            NhanVien nv= taoNhanVien();
//            nvDAO.themNV(nv);
//        docDuLieuLenTable(nvDAO.layTatCaNhanVienDangLamVaoBang(),modelNhanVien);
//        }

    }//GEN-LAST:event_btnThemNhanVienActionPerformed

    private void btnXoaTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTrangActionPerformed
        clearInput();
    }//GEN-LAST:event_btnXoaTrangActionPerformed

    private void btnSuaThongTinNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinNVActionPerformed
//        int index = tblNhanVien.getSelectedRow();
//        if (index==-1){
//            JOptionPane.showMessageDialog(this, "Hãy chọn dòng cần sửa!");
//        }else{
//        if (checkData()){
//            lnvDAO=new DAO_LoaiNhanVien();
//            NhanVien s=nvDAO.layNhanVienBangMa(modelNhanVien.getValueAt(index, 0)+"");            
//
//            s.setCMND(txtCMND.getText());
//            s.setSoDienThoai(txtSoDienThoai.getText());
//            s.setGioiTinh(radNam.isSelected());
//            s.setLuongCoBan(Double.parseDouble(txtLuongCoBan.getText()));
//            String lnv="LNV002";
//            String tLNV="Nhân viên";
//            if(cmbChucVu.getSelectedItem().toString().equals("Quản lý")){
//                lnv="LNV001";
//                tLNV="Quản lý";
//            }
//            s.setLoaiNhanVien(new LoaiNhanVien(lnv,tLNV));           
//            nvDAO.capNhatNV(s);             
//            docDuLieuLenTable(nvDAO.layTatCaNhanVienDangLamVaoBang(), modelNhanVien);
//            JOptionPane.showMessageDialog(this, "Sửa thành công!");
//            clearInput();
//            }
//        }
    }//GEN-LAST:event_btnSuaThongTinNVActionPerformed

    private void btnXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaNhanVienActionPerformed
//        clearInput();
//        int index=tblNhanVien.getSelectedRow();
//        if(index==-1){
//            JOptionPane.showMessageDialog(this, "Hãy chọn một nhân viên để xóa !");
//        }else{
//            int chon= JOptionPane.showConfirmDialog(this, "Bạn có chắn chắn muốn cho nhân viên này thôi việc?", "Hỏi",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
//            if(chon==JOptionPane.YES_OPTION){
//                NhanVien nv=nvDAO.layNhanVienBangMa(modelNhanVien.getValueAt(index, 0)+"");
//                tkDAO.xoaTK(modelNhanVien.getValueAt(index, 0).toString());
//                nvDAO.xoaNV(nv);
//                docDuLieuLenTable(nvDAO.layTatCaNhanVienDangLamVaoBang(), modelNhanVien);
//                JOptionPane.showMessageDialog(this, "Xóa thành công !");
//                clearInput();
//            }
//        }
    }//GEN-LAST:event_btnXoaNhanVienActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        int index=tblNhanVien.getSelectedRow();
        txtTenNhanVien.setText(tblNhanVien.getValueAt(index, 1).toString());
        txtCMND.setText(tblNhanVien.getValueAt(index, 2).toString());
//        if (tblNhanVien.getValueAt(index, 3).toString().equals("Nam")){
//            radNam.setSelected(true);
//        }else{
//            radNu.setSelected(true);
//        }
//        txtSoDienThoai.setText(tblNhanVien.getValueAt(index, 4).toString());
//        cmbChucVu.setSelectedItem(tblNhanVien.getValueAt(index, 5));
//        txtLuongCoBan.setText(tblNhanVien.getValueAt(index, 6).toString());
        
        
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void txtTimKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyReleased
//        String f=txtTimKiem.getText();
//        filter(f);
    }//GEN-LAST:event_txtTimKiemKeyReleased

    private void cmbChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucVuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChucVuActionPerformed

    private void txtTenNhanVien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenNhanVien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenNhanVien1ActionPerformed

    private void cmbChucVu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucVu5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChucVu5ActionPerformed

    private void cmbChucVu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbChucVu6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbChucVu6ActionPerformed
//    private void filter(String s){
//        TableRowSorter<DefaultTableModel> tr=new TableRowSorter<DefaultTableModel>(modelNhanVien);
//        tblNhanVien.setRowSorter(tr);
//        tr.setRowFilter(RowFilter.regexFilter("(?i)"+s));
//
//        
//    }
//    private void docDuLieuLenTable(List<NhanVien> list,DefaultTableModel dtm){
//        dtm.setRowCount(0);
//        String gt;
//        
//        for (NhanVien nv : list) {
//            String taiKhoan ;
//            if(tkDAO.timTaiKhoan(nv.getMaNV())== null)
//                taiKhoan ="Chưa có";
//            else
//                taiKhoan=nv.getMaNV();
//            String cv;
//                if (nv.getLoaiNhanVien().getMaLoaiNV().equals("LNV001")){
//                    cv="Quản lý";
//                }else{
//                    cv="Nhân viên";
//                }
//            if (nv.isGioiTinh()){
//                gt="Nam";
//            }else{
//                gt="Nữ";
//            }
//            
//            dtm.addRow(new Object[]{
//                nv.getMaNV(),nv.getTenNV(),nv.getCMND(),gt,nv.getSoDienThoai(),cv,nv.getLuongCoBan(),taiKhoan,
//                nv.isTrangThai() == true  ? "Đang làm" : "Đã nghĩ việc"
//            });
//            
//        }
//    }
    
    
//    private boolean checkData() {
//        if (txtTenNhanVien.getText().trim().equals("") || txtCMND.getText().trim().equals("") || txtSoDienThoai.getText().trim().equals("") || txtLuongCoBan.getText().trim().equals("") ){
//            JOptionPane.showMessageDialog(this, "Hãy nhập đầy đủ thông tin!");
//            return false;
//        }else{
//            String thongBao="";
//            if (!RegexHelper.regexCMND(txtCMND.getText()))
//                thongBao+="*Số chứng minh nhân gồm 9 số, không chứa ký tự!\n";
//            if(!RegexHelper.regexCustomerName(txtTenNhanVien.getText()))
//                thongBao+="*Tên khách hàng sai định dạng! VD: Lê Anh Thư\n";
//            if(!RegexHelper.regexPhoneNumber(txtSoDienThoai.getText()))
//                thongBao+="*Số điện thoại không chứa ký tự chữ, phải đủ 10 số và bắt đầu bằng các đầu số hợp lệ ( 09, 08, 03, 07, 05 )! VD: 0343229978\n";
//            if (thongBao.isEmpty())
//                return true;
//            else{
//                JOptionPane.showMessageDialog(this, thongBao);
//                return false;
//            }
//        }
//    }
    
//    private NhanVien taoNhanVien() {
//        String tenNV= txtTenNhanVien.getText();
//        String cmnd=txtCMND.getText();
//        String sdt=txtSoDienThoai.getText();
//        boolean gt=radNam.isSelected();
//        double luongCoBan=Double.parseDouble(txtLuongCoBan.getText());
//        String lnv="LNV002";
//        String tLNV="Nhân viên";
//        boolean trangThai = true;
//        if(cmbChucVu.getSelectedItem().toString().equals("Quản lý")){
//            lnv="LNV001";
//            tLNV="Quản lý";
//        }
//        
//        NhanVien nv=new NhanVien(maTuSinh(), tenNV,cmnd, sdt, gt,luongCoBan,trangThai, new LoaiNhanVien(lnv,tLNV));
//        return nv;
//    }
    

    
//    private String maTuSinh() {
//        String ma = "NV";
//        int tachMa;
//        int i = 0, j = 1;
//        int[] dem = new int[999];
//        String id;
//        nvDAO = new DAO_NhanVien();
//        for (NhanVien nv : nvDAO.layTatCa()) {
//            id = nv.getMaNV();
//            tachMa = Integer.parseInt(id.substring(2, 5));
//            dem[i] = tachMa;
//            i++;
//        }
//        i = 0;
//        //gd:  String maPhatSinh= ("SP%3d",i);
//        while (j < 999) {
//            if (dem[i] < j) {
//                if (j <= 9) {
//                    ma += "00" + (j);
//                } else {
//                    ma += "0" + (j);
//                }
//                break;
//            } else if (dem[i] > j) {
//                j = dem[i];
//            } else {
//                i++;
//                j++;
//            }
//        }
//        return ma;
//    }
    private void clearInput(){
        txtCMND.setText("");
//        txtTimKiem.setText("");
        txtSoDienThoai.setText("");
        txtTenNhanVien.setText("");
//        txtLuongCoBan.setText("");
//        txtTenNhanVien.requestFocus();
//        cmbChucVu.setSelectedIndex(1);
//        radNam.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaThongTinNV;
    private javax.swing.JButton btnThemNhanVien;
    private javax.swing.JButton btnXoaNhanVien;
    private javax.swing.JButton btnXoaTrang;
    private javax.swing.JComboBox<String> cmbChucVu;
    private javax.swing.JComboBox<String> cmbChucVu1;
    private javax.swing.JComboBox<String> cmbChucVu2;
    private javax.swing.JComboBox<String> cmbChucVu3;
    private javax.swing.JComboBox<String> cmbChucVu4;
    private javax.swing.JComboBox<String> cmbChucVu5;
    private javax.swing.JComboBox<String> cmbChucVu6;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlDuoi;
    private javax.swing.JPanel pnlGiua;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlNut;
    private javax.swing.JPanel pnlThongTin;
    private javax.swing.JPanel pnlTren;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenNhanVien;
    private javax.swing.JTextField txtTenNhanVien1;
    // End of variables declaration//GEN-END:variables
}
